/*
 * JOCKY Runtime — Timeline & Correlate & Report functions
 * runtime/modules/timeline.c
 *
 * These are orchestrator-level functions called by compiled JOCKY scripts.
 * They gather forensic artefacts from multiple sources and produce
 * structured output (HTML / JSON / CSV).
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include "artifacts/artifact.h"

/* ═══════════════════════════════════════════════════════════════
 * TIMELINE
 * ═══════════════════════════════════════════════════════════════ */

/**
 * Build a host timeline from multiple forensic sources.
 *
 * @param host       Hostname / label
 * @param from_time  ISO-8601 start timestamp
 * @param to_time    ISO-8601 end timestamp
 * @param sources    Comma-separated list: registry,eventlog,prefetch,...
 * @param out_file   Output HTML file path
 */
void jocky_build_timeline(const char *host,
                           const char *from_time,
                           const char *to_time,
                           const char *sources,
                           const char *out_file) {
    fprintf(stdout,
            "[timeline] Building timeline for host=%s from=%s to=%s\n"
            "           sources=[%s] → %s\n",
            host, from_time, to_time, sources, out_file);

    /* ── Parse comma-separated source list ──────────────────────── */
    char src_copy[512];
    strncpy(src_copy, sources, sizeof(src_copy) - 1);

    /* ── Emit HTML report ───────────────────────────────────────── */
    FILE *f = fopen(out_file, "w");
    if (!f) { perror("[timeline] fopen output"); return; }

    fprintf(f,
        "<!DOCTYPE html>\n"
        "<html lang='en'>\n"
        "<head>\n"
        "  <meta charset='UTF-8'>\n"
        "  <title>JOCKY Timeline — %s</title>\n"
        "  <style>\n"
        "    body { font-family: 'Segoe UI', sans-serif; background:#0d1117; color:#c9d1d9; }\n"
        "    h1   { color:#58a6ff; }\n"
        "    table{ border-collapse:collapse; width:100%%; }\n"
        "    th,td{ border:1px solid #30363d; padding:8px 12px; text-align:left; }\n"
        "    th   { background:#161b22; }\n"
        "    tr:nth-child(even){ background:#161b22; }\n"
        "  </style>\n"
        "</head>\n"
        "<body>\n"
        "  <h1>🔍 JOCKY Timeline Report</h1>\n"
        "  <p><strong>Host:</strong> %s</p>\n"
        "  <p><strong>Period:</strong> %s → %s</p>\n"
        "  <p><strong>Sources:</strong> %s</p>\n"
        "  <table>\n"
        "    <thead><tr><th>Timestamp</th><th>Source</th><th>Event</th><th>Details</th></tr></thead>\n"
        "    <tbody>\n",
        host, host, from_time, to_time, sources
    );

    /* TODO: populate from actual source parsers (eventlog, prefetch, etc.) */
    /* Placeholder row */
    time_t now = time(NULL);
    char ts[32];
    strftime(ts, sizeof(ts), "%Y-%m-%dT%H:%M:%SZ", gmtime(&now));
    fprintf(f,
        "      <tr><td>%s</td><td>jocky</td>"
        "<td>Timeline generated</td><td>Sources: %s</td></tr>\n",
        ts, sources
    );

    fprintf(f,
        "    </tbody>\n"
        "  </table>\n"
        "  <p style='color:#8b949e;font-size:0.8em;'>Generated by JOCKY v1.0</p>\n"
        "</body>\n"
        "</html>\n"
    );
    fclose(f);

    fprintf(stdout, "[timeline] Report written → %s\n", out_file);
}

/* ═══════════════════════════════════════════════════════════════
 * CORRELATE (IOC matching)
 * ═══════════════════════════════════════════════════════════════ */

/**
 * Load IOC list and scan an artifact for matches.
 *
 * @param artifact_name  Name of the previously collected artifact
 * @param ioc_list_path  Path to IOC file (one indicator per line, JSON array)
 * @param flag_anomalies 1 = print flagged matches to stdout
 */
void jocky_correlate(const char *artifact_name,
                     const char *ioc_list_path,
                     int         flag_anomalies) {
    fprintf(stdout,
            "[correlate] Matching artifact '%s' against IOC list '%s'\n",
            artifact_name, ioc_list_path);

    FILE *ioc_f = fopen(ioc_list_path, "r");
    if (!ioc_f) {
        fprintf(stderr, "[correlate] Cannot open IOC list: %s\n", ioc_list_path);
        return;
    }

    int hits = 0;
    char ioc[1024];
    while (fgets(ioc, sizeof(ioc), ioc_f)) {
        /* Strip newline */
        ioc[strcspn(ioc, "\r\n")] = '\0';
        if (strlen(ioc) == 0 || ioc[0] == '#') continue;

        /*
         * TODO: search artifact binary blob for IOC string/hash.
         * For now: emit a placeholder match line.
         */
        if (flag_anomalies) {
            fprintf(stdout, "[correlate] IOC checked: %s\n", ioc);
        }
    }
    fclose(ioc_f);

    fprintf(stdout, "[correlate] Done — %d hits\n", hits);
}

/* ═══════════════════════════════════════════════════════════════
 * REPORT GENERATOR
 * ═══════════════════════════════════════════════════════════════ */

static void emit_html(const char *artifact_name, const char *out_file);
static void emit_json(const char *artifact_name, const char *out_file);
static void emit_csv (const char *artifact_name, const char *out_file);

/**
 * Generate a report from a named artifact.
 *
 * @param artifact_name  Artifact identifier
 * @param out_file       Output file path
 * @param format         "html" | "json" | "csv"
 */
void jocky_generate_report(const char *artifact_name,
                            const char *out_file,
                            const char *format) {
    fprintf(stdout, "[report] Generating %s report for '%s' → %s\n",
            format, artifact_name, out_file);

    if (strcmp(format, "json") == 0) emit_json(artifact_name, out_file);
    else if (strcmp(format, "csv") == 0) emit_csv(artifact_name, out_file);
    else emit_html(artifact_name, out_file);
}

static void emit_html(const char *artifact_name, const char *out_file) {
    FILE *f = fopen(out_file, "w");
    if (!f) { perror("[report] fopen"); return; }
    time_t now = time(NULL);
    char ts[32];
    strftime(ts, sizeof(ts), "%Y-%m-%dT%H:%M:%SZ", gmtime(&now));
    fprintf(f,
        "<!DOCTYPE html><html lang='en'><head>"
        "<meta charset='UTF-8'>"
        "<title>JOCKY Report — %s</title>"
        "<style>body{font-family:'Segoe UI',sans-serif;background:#0d1117;color:#c9d1d9;padding:2rem;}"
        "h1{color:#58a6ff;}pre{background:#161b22;padding:1rem;border-radius:6px;overflow:auto;}</style>"
        "</head><body>"
        "<h1>🔬 JOCKY Forensic Report</h1>"
        "<p><strong>Artifact:</strong> %s</p>"
        "<p><strong>Generated:</strong> %s</p>"
        "<pre>// Full artifact data would be decoded and rendered here</pre>"
        "<p style='color:#8b949e;font-size:0.8em;'>Generated by JOCKY v1.0</p>"
        "</body></html>\n",
        artifact_name, artifact_name, ts
    );
    fclose(f);
}

static void emit_json(const char *artifact_name, const char *out_file) {
    FILE *f = fopen(out_file, "w");
    if (!f) { perror("[report] fopen"); return; }
    fprintf(f,
        "{\n"
        "  \"tool\": \"JOCKY\",\n"
        "  \"version\": \"1.0\",\n"
        "  \"artifact\": \"%s\",\n"
        "  \"records\": []\n"
        "}\n",
        artifact_name
    );
    fclose(f);
}

static void emit_csv(const char *artifact_name, const char *out_file) {
    FILE *f = fopen(out_file, "w");
    if (!f) { perror("[report] fopen"); return; }
    fprintf(f, "artifact,record_type,base_addr,size\n");
    fprintf(f, "%s,placeholder,0x0,0\n", artifact_name);
    fclose(f);
}

/* ═══════════════════════════════════════════════════════════════
 * ANALYZE (YARA / plugin dispatch)
 * ═══════════════════════════════════════════════════════════════ */

void jocky_analyze(const char *artifact_name, const char *plugin) {
    fprintf(stdout, "[analyze] Running plugin '%s' on artifact '%s'\n",
            plugin, artifact_name);
    /*
     * TODO: dispatch to YARA scanner or Volatility plugin bridge.
     * Phase 4 extension.
     */
}
