"""
JOCKY AST Builder — visits ANTLR4 parse tree and returns typed AST nodes.
compiler/ast/builder.py

Uses ANTLR element labels (ctx.hostName, ctx.fromTime, ctx.thenBlock, etc.)
so the visitor is a clean 1:1 mapping from parse tree → AST with zero
string-searching or child-counting hacks.
"""
from __future__ import annotations
import sys
import os

# Allow running from different cwd
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from compiler.ast.nodes import (
    Program, CollectStatement, ScanStatement, AnalyzeStatement,
    TimelineStatement, CorrelateStatement, ReportStatement,
    AssignStatement, IfStatement, ForStatement, FuncDecl,
    Source, FilterExpr, Expression,
)

# Generated by ANTLR4 — import lazily so tests don't break before generation
try:
    from compiler.generated.JockyVisitor import JockyVisitor
except ImportError:
    class JockyVisitor:  # type: ignore
        def visit(self, tree): ...
        def visitChildren(self, node): ...


def _strip_quotes(text: str) -> str:
    """Remove surrounding double-quotes from a token's text."""
    if text and len(text) >= 2 and text[0] == '"' and text[-1] == '"':
        return text[1:-1]
    return text


def _get_text(rule_ctx) -> str:
    """Safely extract text from a rule context (id, analyzeTarget, etc.)."""
    if rule_ctx is None:
        return ""
    return rule_ctx.getText()


class ASTBuilder(JockyVisitor):
    """Walk the ANTLR parse tree and produce JOCKY AST nodes."""

    # ─────────────────────────── Program ──────────────────────────────
    def visitProgram(self, ctx):
        stmts = [self.visit(s) for s in ctx.statement()]
        return Program(statements=[s for s in stmts if s is not None])

    # ──────────────────────────── Statements ──────────────────────────────
    def visitStatement(self, ctx):
        return self.visitChildren(ctx)

    # ── collect ──────────────────────────────────────────────────────
    def visitCollectStmt(self, ctx):
        target = ctx.collectTarget().getText()
        source = (
            self.visit(ctx.source())
            if ctx.source()
            else Source(kind="host", value="local", line=ctx.start.line)
        )
        filters = []
        if ctx.filterClause():
            filters = [self.visit(f) for f in ctx.filterClause().filterExpr()]
        export_name = None
        if ctx.exportClause():
            export_name = _strip_quotes(ctx.exportClause().exportName.text)
        return CollectStatement(
            target=target,
            source=source,
            filters=filters,
            export_name=export_name,
            line=ctx.start.line,
        )

    # ── scan ─────────────────────────────────────────────────────────
    def visitScanStmt(self, ctx):
        target = ctx.scanTarget().getText().replace(" ", "_")
        interface = _get_text(ctx.ifaceName) if ctx.ifaceName else None
        filter_expr = self.visit(ctx.filterBody) if ctx.filterBody else None
        return ScanStatement(
            target=target,
            interface=interface,
            filter_expr=filter_expr,
            line=ctx.start.line,
        )

    # ── analyze ──────────────────────────────────────────────────────
    def visitAnalyzeStmt(self, ctx):
        # targetRef is an analyzeTarget rule (id | STRING)
        target_ctx = ctx.targetRef
        target_text = _strip_quotes(_get_text(target_ctx))
        plugin = _strip_quotes(ctx.pluginName.text)
        threshold = float(ctx.thresholdVal.text) if ctx.thresholdVal else None
        return AnalyzeStatement(
            target=target_text,
            plugin=plugin,
            threshold=threshold,
            line=ctx.start.line,
        )

    # ── timeline ─────────────────────────────────────────────────────
    def visitTimelineStmt(self, ctx):
        # All labeled — no guessing needed
        host = _strip_quotes(_get_text(ctx.hostName))
        from_time = _strip_quotes(_get_text(ctx.fromTime))
        to_time = _strip_quotes(_get_text(ctx.toTime))
        sources = [s.getText() for s in ctx.timelineSource()]
        output_file = (
            _strip_quotes(ctx.outputFile.text) if ctx.outputFile else None
        )
        return TimelineStatement(
            host=host,
            from_time=from_time,
            to_time=to_time,
            sources=sources,
            output_file=output_file,
            line=ctx.start.line,
        )

    # ── correlate ────────────────────────────────────────────────────
    def visitCorrelateStmt(self, ctx):
        data = _strip_quotes(_get_text(ctx.dataRef))
        ioc_list = _strip_quotes(ctx.iocPath.text)
        # Grammar: 'correlate' dataRef 'with' iocPath ('flag' 'anomalies')?
        # 4 children = no flag, 6 children = flag present
        flag = ctx.getChildCount() > 4
        return CorrelateStatement(
            data=data,
            ioc_list=ioc_list,
            flag_anomalies=flag,
            line=ctx.start.line,
        )

    # ── report ───────────────────────────────────────────────────────
    def visitReportStmt(self, ctx):
        target = _strip_quotes(_get_text(ctx.targetRef))
        filename = _strip_quotes(ctx.outputName.text)
        fmt = "html"  # default
        if ctx.formatClause():
            fmt = ctx.formatClause().formatType.text
        return ReportStatement(
            target=target,
            filename=filename,
            format=fmt,
            line=ctx.start.line,
        )

    # ── assign ───────────────────────────────────────────────────────
    def visitAssignStmt(self, ctx):
        name = _get_text(ctx.varName)
        val = self.visit(ctx.assignValue)
        return AssignStatement(name=name, value=val, line=ctx.start.line)

    # ── if/else ──────────────────────────────────────────────────────
    def visitIfStmt(self, ctx):
        cond = self.visit(ctx.condition)
        then_stmts = [self.visit(s) for s in ctx.thenBlock.statement()]
        else_stmts = []
        if ctx.elseBlock:
            else_stmts = [self.visit(s) for s in ctx.elseBlock.statement()]
        return IfStatement(
            condition=cond,
            then_block=[s for s in then_stmts if s is not None],
            else_block=[s for s in else_stmts if s is not None],
            line=ctx.start.line,
        )

    # ── for ──────────────────────────────────────────────────────────
    def visitForStmt(self, ctx):
        var = _get_text(ctx.loopVar)
        iterable = _get_text(ctx.iterName)
        body = [self.visit(s) for s in ctx.forBody.statement()]
        return ForStatement(
            var=var,
            iterable=iterable,
            body=[s for s in body if s is not None],
            line=ctx.start.line,
        )

    # ── function ─────────────────────────────────────────────────────
    def visitFuncDecl(self, ctx):
        name = _get_text(ctx.funcName)
        params = []
        if ctx.paramList():
            params = [_get_text(p) for p in ctx.paramList().id_()]
        body = [self.visit(s) for s in ctx.funcBody.statement()]
        return FuncDecl(
            name=name,
            params=params,
            body=[s for s in body if s is not None],
            line=ctx.start.line,
        )

    # ────────────────────────────── Source ────────────────────────────────
    def visitSource(self, ctx):
        if ctx.pidValue:
            # pidRef = NUMBER | id
            pid_ctx = ctx.pidValue
            if pid_ctx.NUMBER():
                return Source(kind="pid", value=int(pid_ctx.NUMBER().getText()), line=ctx.start.line)
            else:
                return Source(kind="pid", value=_get_text(pid_ctx.id_()), line=ctx.start.line)
        elif ctx.hostValue:
            # hostRef = STRING | id
            host_ctx = ctx.hostValue
            if host_ctx.STRING():
                return Source(kind="host", value=_strip_quotes(host_ctx.STRING().getText()), line=ctx.start.line)
            else:
                return Source(kind="host", value=_get_text(host_ctx.id_()), line=ctx.start.line)
        elif ctx.idValue:
            return Source(kind="identifier", value=_get_text(ctx.idValue), line=ctx.start.line)
        else:
            return Source(kind="identifier", value=ctx.getText(), line=ctx.start.line)

    # ─────────────────────────── Filter exprs ─────────────────────────────
    def visitFilterExpr(self, ctx):
        field_name = _get_text(ctx.fieldName)
        op = ctx.filterOp().getText() if ctx.filterOp() else "in"

        # filterValue = STRING | NUMBER | identifierList | id
        fv = ctx.filterValue()
        if fv.STRING():
            val = _strip_quotes(fv.STRING().getText())
        elif fv.NUMBER():
            val = float(fv.NUMBER().getText())
        elif fv.identifierList():
            val = [_get_text(i) for i in fv.identifierList().id_()]
        elif fv.id_():
            val = _get_text(fv.id_())
        else:
            val = fv.getText()

        return FilterExpr(field=field_name, operator=op, value=val, line=ctx.start.line)

    # ─────────────────────────── Expressions ──────────────────────────────
    def visitExpr(self, ctx):
        children = ctx.getChildCount()

        # primary (single child)
        if children == 1:
            return self.visit(ctx.primary())

        # unary: 'not' expr
        if children == 2:
            op = ctx.getChild(0).getText()
            right = self.visit(ctx.expr(0))
            return Expression(operator=op, right=right, line=ctx.start.line)

        # binary: expr op expr  |  expr 'contains' expr  |  expr 'matches' STRING
        if children == 3:
            op_text = ctx.getChild(1).getText()
            left = self.visit(ctx.expr(0))
            # 'matches' has STRING as third child, not expr
            if op_text == "matches":
                right = Expression(
                    value=_strip_quotes(ctx.STRING().getText()),
                    line=ctx.start.line,
                )
            else:
                right = self.visit(ctx.expr(1))
            return Expression(operator=op_text, left=left, right=right, line=ctx.start.line)

        return self.visitChildren(ctx)

    def visitPrimary(self, ctx):
        if ctx.NUMBER():
            return Expression(value=float(ctx.NUMBER().getText()), line=ctx.start.line)
        if ctx.STRING():
            return Expression(value=_strip_quotes(ctx.STRING().getText()), line=ctx.start.line)
        if ctx.BOOL():
            return Expression(value=ctx.BOOL().getText() == "true", line=ctx.start.line)
        if ctx.id_():
            return Expression(value=_get_text(ctx.id_()), line=ctx.start.line)
        if ctx.expr():
            return self.visit(ctx.expr())
        return Expression(value=ctx.getText(), line=ctx.start.line)
