"""
JOCKY AST Builder — visits ANTLR4 parse tree and returns typed AST nodes.
compiler/ast/builder.py
"""
from __future__ import annotations
import sys
import os

# Allow running from different cwd
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from antlr4 import ParserRuleContext
from compiler.ast.nodes import (
    Program, CollectStatement, ScanStatement, AnalyzeStatement,
    TimelineStatement, CorrelateStatement, ReportStatement,
    AssignStatement, IfStatement, ForStatement, FuncDecl,
    Source, FilterExpr, Expression,
)

# Generated by ANTLR4 — import lazily so tests don't break before generation
try:
    from compiler.generated.JockyVisitor import JockyVisitor
except ImportError:
    class JockyVisitor:  # type: ignore
        def visit(self, tree): ...
        def visitChildren(self, node): ...


class ASTBuilder(JockyVisitor):
    """Walk the ANTLR parse tree and produce JOCKY AST nodes."""

    # ─────────────────────────────── Program ──────────────────────────────
    def visitProgram(self, ctx):
        stmts = [self.visit(s) for s in ctx.statement()]
        return Program(statements=[s for s in stmts if s is not None])

    # ──────────────────────────── Statements ──────────────────────────────
    def visitStatement(self, ctx):
        return self.visitChildren(ctx)

    def visitCollectStmt(self, ctx):
        target = ctx.collectTarget().getText()
        source = self.visit(ctx.source()) if ctx.source() else Source(kind="host", value="local", line=ctx.start.line)
        filters = []
        if ctx.filterClause():
            filters = [self.visit(f) for f in ctx.filterClause().filterExpr()]
        export_name = None
        if ctx.exportClause():
            raw = ctx.exportClause().STRING().getText()
            export_name = raw.strip('"')
        return CollectStatement(
            target=target,
            source=source,
            filters=filters,
            export_name=export_name,
            line=ctx.start.line,
        )

    def visitScanStmt(self, ctx):
        target = ctx.scanTarget().getText().replace(" ", "_")
        interface = self._get_id_text(ctx)
        filter_expr = self.visit(ctx.expr()) if ctx.expr() else None
        return ScanStatement(
            target=target,
            interface=interface,
            filter_expr=filter_expr,
            line=ctx.start.line,
        )

    def visitAnalyzeStmt(self, ctx):
        ident = self._get_id_text(ctx) or (ctx.STRING().getText().strip('"') if ctx.STRING() else "")
        plugin = ctx.STRING().getText().strip('"') if ctx.STRING() else ""
        threshold = float(ctx.NUMBER().getText()) if ctx.NUMBER() else None
        return AnalyzeStatement(
            target=ident, plugin=plugin, threshold=threshold,
            line=ctx.start.line,
        )

    def visitTimelineStmt(self, ctx):
        strings = [s.getText().strip('"') for s in ctx.STRING()]
        ts = [t.getText().strip('"') for t in ctx.TIMESTAMP()] if ctx.TIMESTAMP() else []
        host_id = self._get_id_text(ctx)
        
        if host_id:
            host = host_id
            if len(ts) >= 2:
                from_time = ts[0]
                to_time = ts[1]
                output_file = strings[0] if strings else None
            elif len(strings) >= 2:
                from_time = strings[0]
                to_time = strings[1]
                output_file = strings[2] if len(strings) > 2 else None
            else:
                from_time = ts[0] if ts else ""
                to_time = strings[0] if strings else ""
                output_file = None
        else:
            host = strings[0] if strings else ""
            if len(ts) >= 2:
                from_time = ts[0]
                to_time = ts[1]
                output_file = strings[1] if len(strings) > 1 else None
            elif len(strings) >= 3:
                from_time = strings[1]
                to_time = strings[2]
                output_file = strings[3] if len(strings) > 3 else None
            else:
                from_time = ts[0] if ts else ""
                to_time = ts[1] if len(ts) > 1 else ""
                output_file = None

        sources = [s.getText() for s in ctx.timelineSource()]
        return TimelineStatement(
            host=host,
            from_time=from_time,
            to_time=to_time,
            sources=sources,
            output_file=output_file,
            line=ctx.start.line,
        )

    def visitCorrelateStmt(self, ctx):
        ident = self._get_id_text(ctx)
        strings = [s.getText().strip('"') for s in ctx.STRING()]
        if ident:
            ioc_list = strings[0] if strings else ""
        else:
            ident = strings[0] if strings else ""
            ioc_list = strings[1] if len(strings) > 1 else ""
        flag = "flag" in ctx.getText() and "anomalies" in ctx.getText()
        return CorrelateStatement(
            data=ident, ioc_list=ioc_list, flag_anomalies=flag,
            line=ctx.start.line,
        )

    def visitReportStmt(self, ctx):
        ident = self._get_id_text(ctx)
        strings = [s.getText().strip('"') for s in ctx.STRING()]
        if ident:
            filename = strings[0] if strings else ""
        else:
            ident = strings[0] if strings else ""
            filename = strings[1] if len(strings) > 1 else ""
        fmt = "html"
        text = ctx.getText().lower()
        for candidate in ("json", "csv", "html"):
            if candidate in text:
                fmt = candidate
                break
        return ReportStatement(
            target=ident, filename=filename, format=fmt,
            line=ctx.start.line,
        )

    def visitAssignStmt(self, ctx):
        name = self._get_id_text(ctx) or "var"
        val = self.visit(ctx.expr())
        return AssignStatement(name=name, value=val, line=ctx.start.line)

    def visitIfStmt(self, ctx):
        cond = self.visit(ctx.expr())
        # Split on 'else' — the grammar encodes them as two repeated blocks
        then_stmts = [self.visit(s) for s in ctx.statement(0).children if isinstance(s, ParserRuleContext)]  # type: ignore
        else_stmts = []
        if len(ctx.children) > 5:  # has else branch
            else_stmts = [self.visit(s) for s in ctx.statement(1).children if isinstance(s, ParserRuleContext)]  # type: ignore
        return IfStatement(
            condition=cond, then_block=then_stmts, else_block=else_stmts,
            line=ctx.start.line,
        )

    def visitForStmt(self, ctx):
        ids = self._get_id_list(ctx)
        var = ids[0] if len(ids) > 0 else "item"
        iterable = ids[1] if len(ids) > 1 else "items"
        body = [self.visit(s) for s in ctx.statement()]
        return ForStatement(var=var, iterable=iterable, body=body, line=ctx.start.line)

    def visitFuncDecl(self, ctx):
        name = self._get_id_text(ctx) or "anonymous"
        params = []
        if ctx.paramList():
            params = self._get_id_list(ctx.paramList())
        body = [self.visit(s) for s in ctx.statement()]
        return FuncDecl(name=name, params=params, body=body, line=ctx.start.line)

    # ────────────────────────────── Source ────────────────────────────────
    def visitSource(self, ctx):
        text = ctx.getText()
        if ctx.NUMBER():
            return Source(kind="pid", value=int(ctx.NUMBER().getText()), line=ctx.start.line)
        elif ctx.STRING():
            return Source(kind="host", value=ctx.STRING().getText().strip('"'), line=ctx.start.line)
        elif hasattr(ctx, "id_") and ctx.id_():
            kind = "pid" if "pid" in text else ("host" if "host" in text else "identifier")
            return Source(kind=kind, value=ctx.id_().getText(), line=ctx.start.line)
        else:
            return Source(kind="identifier", value=text, line=ctx.start.line)

    # ─────────────────────────── Filter exprs ─────────────────────────────
    def visitFilterExpr(self, ctx):
        ids = self._get_id_list(ctx)
        field_name = ids[0] if ids else "field"
        op = ctx.filterOp().getText() if ctx.filterOp() else "in"
        if ctx.STRING():
            val = ctx.STRING().getText().strip('"')
        elif ctx.NUMBER():
            val = float(ctx.NUMBER().getText())
        elif ctx.identifierList():
            val = self._get_id_list(ctx.identifierList())
        elif len(ids) > 1:
            val = ids[1]
        else:
            val = None
        return FilterExpr(field=field_name, operator=op, value=val, line=ctx.start.line)

    # ─────────────────────────── Expressions ──────────────────────────────
    def visitExpr(self, ctx):
        if ctx.getChildCount() == 1:
            return self.visit(ctx.primary())
        if ctx.getChildCount() == 2:
            # unary not
            op = ctx.getChild(0).getText()
            right = self.visit(ctx.expr(0))
            return Expression(operator=op, right=right, line=ctx.start.line)
        if ctx.getChildCount() == 3:
            op = ctx.getChild(1).getText()
            left = self.visit(ctx.expr(0))
            right = self.visit(ctx.expr(1))
            return Expression(operator=op, left=left, right=right, line=ctx.start.line)
        return self.visitChildren(ctx)

    def visitPrimary(self, ctx):
        text = ctx.getText()
        if ctx.NUMBER():
            return Expression(value=float(ctx.NUMBER().getText()), line=ctx.start.line)
        if ctx.STRING():
            return Expression(value=ctx.STRING().getText().strip('"'), line=ctx.start.line)
        if ctx.BOOL():
            return Expression(value=text == "true", line=ctx.start.line)
        id_text = self._get_id_text(ctx)
        if id_text is not None:
            return Expression(value=id_text, line=ctx.start.line)
        if ctx.expr():
            return self.visit(ctx.expr())
        return Expression(value=text, line=ctx.start.line)

    # ────────────────────────── Helper methods ────────────────────────────
    def _get_id_text(self, ctx) -> str | None:
        if hasattr(ctx, "id_") and ctx.id_():
            res = ctx.id_()
            if isinstance(res, list):
                return res[0].getText() if res else None
            return res.getText()
        if hasattr(ctx, "IDENTIFIER") and ctx.IDENTIFIER():
            res = ctx.IDENTIFIER()
            if isinstance(res, list):
                return res[0].getText() if res else None
            return res.getText()
        return None

    def _get_id_list(self, ctx) -> list[str]:
        if hasattr(ctx, "id_") and ctx.id_():
            res = ctx.id_()
            if isinstance(res, list):
                return [x.getText() for x in res]
            return [res.getText()]
        if hasattr(ctx, "IDENTIFIER") and ctx.IDENTIFIER():
            res = ctx.IDENTIFIER()
            if isinstance(res, list):
                return [x.getText() for x in res]
            return [res.getText()]
        return []
